# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/congestion_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/congestion_control.proto',
  package='congestioncontrol',
  syntax='proto3',
  serialized_options=b'B\026CongestionControlProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fprotos/congestion_control.proto\x12\x11\x63ongestioncontrol\"S\n\x12TransmissionStatus\x12\x13\n\x0bparameter_1\x18\x01 \x01(\x05\x12\x13\n\x0bparameter_2\x18\x02 \x01(\x05\x12\x13\n\x0bparameter_3\x18\x03 \x01(\x05\"\x1d\n\x06\x41\x63tion\x12\x13\n\x0b\x63wnd_update\x18\x01 \x01(\x05\x32x\n\x11\x43ongestionControl\x12\x63\n\x19OptimizeCongestionControl\x12%.congestioncontrol.TransmissionStatus\x1a\x19.congestioncontrol.Action\"\x00(\x01\x30\x01\x42\x1a\x42\x16\x43ongestionControlProtoP\x01\x62\x06proto3'
)




_TRANSMISSIONSTATUS = _descriptor.Descriptor(
  name='TransmissionStatus',
  full_name='congestioncontrol.TransmissionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameter_1', full_name='congestioncontrol.TransmissionStatus.parameter_1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter_2', full_name='congestioncontrol.TransmissionStatus.parameter_2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter_3', full_name='congestioncontrol.TransmissionStatus.parameter_3', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=137,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='congestioncontrol.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cwnd_update', full_name='congestioncontrol.Action.cwnd_update', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['TransmissionStatus'] = _TRANSMISSIONSTATUS
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransmissionStatus = _reflection.GeneratedProtocolMessageType('TransmissionStatus', (_message.Message,), {
  'DESCRIPTOR' : _TRANSMISSIONSTATUS,
  '__module__' : 'protos.congestion_control_pb2'
  # @@protoc_insertion_point(class_scope:congestioncontrol.TransmissionStatus)
  })
_sym_db.RegisterMessage(TransmissionStatus)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'protos.congestion_control_pb2'
  # @@protoc_insertion_point(class_scope:congestioncontrol.Action)
  })
_sym_db.RegisterMessage(Action)


DESCRIPTOR._options = None

_CONGESTIONCONTROL = _descriptor.ServiceDescriptor(
  name='CongestionControl',
  full_name='congestioncontrol.CongestionControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='OptimizeCongestionControl',
    full_name='congestioncontrol.CongestionControl.OptimizeCongestionControl',
    index=0,
    containing_service=None,
    input_type=_TRANSMISSIONSTATUS,
    output_type=_ACTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONGESTIONCONTROL)

DESCRIPTOR.services_by_name['CongestionControl'] = _CONGESTIONCONTROL

# @@protoc_insertion_point(module_scope)
